apiVersion: v1
kind: LimitRange
metadata:
  name: optio-default-resources
  namespace: optio
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      default:
        cpu: 250m
        memory: 256Mi
